import { Difficulty, Language, type Question } from "../backend";

const bq = (
  id: number,
  cat: string,
  text: string,
  opts: string[],
  ci: number,
  diff = Difficulty.medium,
): Question => ({
  id: BigInt(id),
  category: cat,
  language: Language.bengali,
  questionText: text,
  options: opts,
  correctIndex: BigInt(ci),
  difficulty: diff,
});

const eq = (
  id: number,
  cat: string,
  text: string,
  opts: string[],
  ci: number,
  diff = Difficulty.medium,
): Question => ({
  id: BigInt(id),
  category: cat,
  language: Language.english,
  questionText: text,
  options: opts,
  correctIndex: BigInt(ci),
  difficulty: diff,
});

export const SAMPLE_QUESTIONS: Question[] = [
  // ===== General Knowledge - Bengali =====
  bq(
    1001,
    "General Knowledge",
    "বাংলাদেশের জাতীয় ফুল কোনটি?",
    ["গোলাপ", "শাপলা", "জবা", "পদ্ম"],
    1,
    Difficulty.easy,
  ),
  bq(
    1002,
    "General Knowledge",
    "বাংলাদেশের রাজধানী কোথায়?",
    ["চট্টগ্রাম", "সিলেট", "ঢাকা", "রাজশাহী"],
    2,
    Difficulty.easy,
  ),
  bq(
    1003,
    "General Knowledge",
    "পৃথিবীর সবচেয়ে বড় মহাসাগর কোনটি?",
    ["আটলান্টিক", "ভারত", "প্রশান্ত", "আর্কটিক"],
    2,
    Difficulty.easy,
  ),
  bq(
    1004,
    "General Knowledge",
    "বাংলাদেশের মুক্তিযুদ্ধ কত সালে হয়েছিল?",
    ["১৯৬৯", "১৯৭০", "১৯৭১", "১৯৭২"],
    2,
    Difficulty.easy,
  ),
  bq(
    1005,
    "General Knowledge",
    "বাংলাদেশের জাতীয় পাখি কোনটি?",
    ["ময়ূর", "দোয়েল", "কোকিল", "শালিক"],
    1,
    Difficulty.easy,
  ),
  bq(
    1006,
    "General Knowledge",
    "সূর্য থেকে পৃথিবীর দূরত্ব প্রায় কত?",
    ["১৪ কোটি কিমি", "১৫ কোটি কিমি", "১৬ কোটি কিমি", "১৭ কোটি কিমি"],
    1,
  ),
  bq(
    1007,
    "General Knowledge",
    "বাংলাদেশের জাতীয় খেলা কী?",
    ["ক্রিকেট", "ফুটবল", "হা-ডু-ডু (কাবাডি)", "হকি"],
    2,
  ),
  bq(
    1008,
    "General Knowledge",
    "UNESCO কোন বছর বাংলাকে আন্তর্জাতিক মাতৃভাষা দিবস হিসেবে স্বীকৃতি দেয়?",
    ["১৯৯৮", "১৯৯৯", "২০০০", "২০০১"],
    1,
  ),
  bq(
    1009,
    "General Knowledge",
    "বাংলাদেশের মোট জেলা কতটি?",
    ["৬০টি", "৬৪টি", "৬৮টি", "৭২টি"],
    1,
    Difficulty.easy,
  ),
  bq(
    1010,
    "General Knowledge",
    "বাংলাদেশের জাতীয় মাছ কোনটি?",
    ["ইলিশ", "রুই", "কাতলা", "শোল"],
    0,
    Difficulty.easy,
  ),
  bq(
    1011,
    "General Knowledge",
    "বাংলাদেশের জাতীয় ফল কী?",
    ["আম", "কাঁঠাল", "কলা", "পেঁপে"],
    1,
    Difficulty.easy,
  ),
  bq(
    1012,
    "General Knowledge",
    "পৃথিবীর সবচেয়ে বড় দেশ কোনটি?",
    ["চীন", "কানাডা", "রাশিয়া", "যুক্তরাষ্ট্র"],
    2,
    Difficulty.easy,
  ),
  bq(
    1013,
    "General Knowledge",
    "সুন্দরবন কোন দুটি দেশে অবস্থিত?",
    ["ভারত ও পাকিস্তান", "বাংলাদেশ ও ভারত", "বাংলাদেশ ও মিয়ানমার", "ভারত ও নেপাল"],
    1,
    Difficulty.easy,
  ),
  bq(
    1014,
    "General Knowledge",
    "বাংলাদেশের প্রথম প্রধানমন্ত্রী কে ছিলেন?",
    ["শেখ মুজিবুর রহমান", "তাজউদ্দীন আহমদ", "মোশতাক আহমেদ", "জিয়াউর রহমান"],
    1,
  ),
  bq(
    1015,
    "General Knowledge",
    "জাতিসংঘের সদর দফতর কোথায়?",
    ["লন্ডন", "প্যারিস", "নিউইয়র্ক", "জেনেভা"],
    2,
    Difficulty.easy,
  ),
  bq(
    1016,
    "General Knowledge",
    "পৃথিবীর সবচেয়ে ছোট দেশ কোনটি?",
    ["মোনাকো", "সান মারিনো", "লিখটেনস্টাইন", "ভ্যাটিকান সিটি"],
    3,
  ),
  bq(
    1017,
    "General Knowledge",
    "ইন্টারনেটের আবিষ্কারক কে?",
    ["বিল গেটস", "টিম বার্নার্স-লি", "স্টিভ জবস", "মার্ক জাকারবার্গ"],
    1,
  ),
  bq(
    1018,
    "General Knowledge",
    "বাংলাদেশের সর্বোচ্চ পর্বতশৃঙ্গ কোনটি?",
    ["তাজিং ডং", "কেওক্রাডং", "চাকতালং", "মোদকমুয়াল"],
    0,
    Difficulty.hard,
  ),
  bq(
    1019,
    "General Knowledge",
    "মানবদেহের স্বাভাবিক তাপমাত্রা কত?",
    ["৩৫°C", "৩৬°C", "৩৭°C", "৩৮°C"],
    2,
    Difficulty.easy,
  ),
  bq(
    1020,
    "General Knowledge",
    "বিশ্বের সবচেয়ে জনবহুল দেশ কোনটি?",
    ["ভারত", "চীন", "যুক্তরাষ্ট্র", "ইন্দোনেশিয়া"],
    0,
    Difficulty.easy,
  ),
  bq(
    1021,
    "General Knowledge",
    "বাংলাদেশের জাতীয় সংগীতের রচয়িতা কে?",
    ["কাজী নজরুল ইসলাম", "রবীন্দ্রনাথ ঠাকুর", "জীবনানন্দ দাশ", "সুকান্ত ভট্টাচার্য"],
    1,
    Difficulty.easy,
  ),
  bq(
    1022,
    "General Knowledge",
    "পৃথিবীর দীর্ঘতম নদী কোনটি?",
    ["আমাজন", "নীলনদ", "ইয়াংসি", "মিসিসিপি"],
    1,
    Difficulty.easy,
  ),
  bq(
    1023,
    "General Knowledge",
    "বাংলাদেশ কত সালে জাতিসংঘের সদস্য হয়?",
    ["১৯৭২", "১৯৭৩", "১৯৭৪", "১৯৭৫"],
    2,
  ),
  bq(
    1024,
    "General Knowledge",
    "বিশ্বের সবচেয়ে বড় মরুভূমি কোনটি?",
    ["গোবি", "সাহারা", "অ্যান্টার্কটিকা", "আরব"],
    2,
    Difficulty.hard,
  ),
  bq(
    1025,
    "General Knowledge",
    "ঢাকা বিশ্ববিদ্যালয় কত সালে প্রতিষ্ঠিত হয়?",
    ["১৯১৯", "১৯২০", "১৯২১", "১৯২২"],
    2,
  ),
  bq(
    1026,
    "General Knowledge",
    "বাংলাদেশের জাতীয় সংসদের আসন সংখ্যা কত?",
    ["২৫০টি", "৩০০টি", "৩৫০টি", "৪০০টি"],
    1,
  ),
  bq(
    1027,
    "General Knowledge",
    "পৃথিবীর সবচেয়ে উঁচু পর্বতশৃঙ্গ কোনটি?",
    ["K2", "কাঞ্চনজঙ্ঘা", "এভারেস্ট", "লোৎসে"],
    2,
    Difficulty.easy,
  ),
  bq(
    1028,
    "General Knowledge",
    "বাংলাদেশের মুদ্রার নাম কী?",
    ["রুপি", "টাকা", "পাউন্ড", "ডলার"],
    1,
    Difficulty.easy,
  ),
  bq(
    1029,
    "General Knowledge",
    "বিশ্বের কতটি দেশ আছে?",
    ["১৮০টি", "১৯০টি", "১৯৫টি", "২০০টি"],
    2,
  ),
  bq(
    1030,
    "General Knowledge",
    "বাংলাদেশের প্রধান রফতানি পণ্য কী?",
    ["চামড়া", "তৈরি পোশাক", "চিংড়ি", "পাট"],
    1,
    Difficulty.easy,
  ),

  // ===== Science - Bengali =====
  bq(
    2001,
    "Science",
    "পানির রাসায়নিক সংকেত কী?",
    ["CO₂", "H₂O", "NaCl", "O₂"],
    1,
    Difficulty.easy,
  ),
  bq(
    2002,
    "Science",
    "আলোর গতিবেগ প্রতি সেকেন্ডে কত?",
    ["২ লক্ষ কিমি", "৩ লক্ষ কিমি", "৪ লক্ষ কিমি", "১ লক্ষ কিমি"],
    1,
    Difficulty.easy,
  ),
  bq(
    2003,
    "Science",
    "মানব দেহে হাড়ের সংখ্যা কত?",
    ["২০৬", "২০৮", "২১০", "২০৪"],
    0,
  ),
  bq(
    2004,
    "Science",
    "কোন গ্যাস বায়ুমণ্ডলে সবচেয়ে বেশি আছে?",
    ["অক্সিজেন", "কার্বন ডাইঅক্সাইড", "নাইট্রোজেন", "হিলিয়াম"],
    2,
    Difficulty.easy,
  ),
  bq(
    2005,
    "Science",
    "পৃথিবীর নিজ অক্ষের চারপাশে একবার ঘুরতে কত সময় লাগে?",
    ["১২ ঘণ্টা", "২৪ ঘণ্টা", "৪৮ ঘণ্টা", "৩৬ ঘণ্টা"],
    1,
    Difficulty.easy,
  ),
  bq(
    2006,
    "Science",
    "সূর্যের আলো পৃথিবীতে পৌঁছাতে কত মিনিট লাগে?",
    ["৫ মিনিট", "৮ মিনিট", "১২ মিনিট", "১৫ মিনিট"],
    1,
  ),
  bq(
    2007,
    "Science",
    "DNA-এর পূর্ণরূপ কী?",
    [
      "Deoxyribonucleic Acid",
      "Diribonuclear Acid",
      "Deoxyribose Acid",
      "Dynamic Nucleic Acid",
    ],
    0,
    Difficulty.hard,
  ),
  bq(
    2008,
    "Science",
    "মানবদেহের সবচেয়ে বড় অঙ্গ কোনটি?",
    ["হৃদপিণ্ড", "মস্তিষ্ক", "ত্বক", "যকৃৎ"],
    2,
  ),
  bq(
    2009,
    "Science",
    "পরমাণুর কেন্দ্রে কী থাকে?",
    ["ইলেকট্রন", "নিউক্লিয়াস", "প্রোটন", "নিউট্রন"],
    1,
  ),
  bq(
    2010,
    "Science",
    "সবুজ উদ্ভিদ সালোকসংশ্লেষণে কোন গ্যাস ব্যবহার করে?",
    ["অক্সিজেন", "নাইট্রোজেন", "কার্বন ডাইঅক্সাইড", "হাইড্রোজেন"],
    2,
  ),
  bq(
    2011,
    "Science",
    "মানুষের রক্তের স্বাভাবিক pH মান কত?",
    ["৬.৮", "৭.৪", "৮.০", "৫.৫"],
    1,
    Difficulty.hard,
  ),
  bq(
    2012,
    "Science",
    "বিদ্যুৎ পরিমাপের একক কী?",
    ["ওয়াট", "অ্যাম্পিয়ার", "ভোল্ট", "ওহম"],
    0,
  ),
  bq(
    2013,
    "Science",
    "পেনিসিলিন আবিষ্কার করেন কে?",
    ["মেরি কুরি", "লুই পাস্তুর", "আলেকজান্ডার ফ্লেমিং", "এডওয়ার্ড জেনার"],
    2,
  ),
  bq(
    2014,
    "Science",
    "মানবদেহের সবচেয়ে ছোট হাড় কোনটি?",
    ["স্টেপস (কানের হাড়)", "প্যাটেলা", "ক্লেভিকল", "কার্পাল"],
    0,
    Difficulty.hard,
  ),
  bq(
    2015,
    "Science",
    "পৃথিবীর সবচেয়ে বেশি ব্যবহৃত ধাতু কোনটি?",
    ["লোহা", "তামা", "অ্যালুমিনিয়াম", "সোনা"],
    0,
    Difficulty.easy,
  ),
  bq(
    2016,
    "Science",
    "আইনস্টাইনের বিখ্যাত সমীকরণ কোনটি?",
    ["F=ma", "E=mc²", "V=IR", "P=mv"],
    1,
    Difficulty.easy,
  ),
  bq(
    2017,
    "Science",
    "সূর্য একটি কী?",
    ["গ্রহ", "উপগ্রহ", "নক্ষত্র", "ধূমকেতু"],
    2,
    Difficulty.easy,
  ),
  bq(
    2018,
    "Science",
    "মানবদেহে কতটি কিডনি থাকে?",
    ["১টি", "২টি", "৩টি", "৪টি"],
    1,
    Difficulty.easy,
  ),
  bq(2019, "Science", "সোডিয়ামের রাসায়নিক প্রতীক কী?", ["So", "Sd", "Na", "So"], 2),
  bq(
    2020,
    "Science",
    "হৃদপিণ্ডে কতটি প্রকোষ্ঠ থাকে?",
    ["২টি", "৩টি", "৪টি", "৫টি"],
    2,
    Difficulty.easy,
  ),
  bq(
    2021,
    "Science",
    "কোন ভিটামিনের অভাবে রিকেটস রোগ হয়?",
    ["ভিটামিন A", "ভিটামিন B", "ভিটামিন C", "ভিটামিন D"],
    3,
  ),
  bq(
    2022,
    "Science",
    "বিদ্যুৎ পরিবাহিতার ভালো উপাদান কোনটি?",
    ["কাচ", "রাবার", "তামা", "প্লাস্টিক"],
    2,
    Difficulty.easy,
  ),
  bq(
    2023,
    "Science",
    "মানুষের চোখে কোন ধরনের লেন্স আছে?",
    ["সমতল লেন্স", "উত্তল লেন্স", "অবতল লেন্স", "দ্বিতল লেন্স"],
    1,
  ),
  bq(
    2024,
    "Science",
    "পৃথিবীর বায়ুমণ্ডলে অক্সিজেনের পরিমাণ কত?",
    ["১৫%", "২১%", "২৫%", "৩০%"],
    1,
  ),
  bq(
    2025,
    "Science",
    "সবচেয়ে হালকা মৌল কোনটি?",
    ["হিলিয়াম", "হাইড্রোজেন", "লিথিয়াম", "নিয়ন"],
    1,
    Difficulty.easy,
  ),
  bq(
    2026,
    "Science",
    "প্রোটিন তৈরিতে কোনটি প্রয়োজন?",
    ["ফ্যাটি অ্যাসিড", "অ্যামিনো অ্যাসিড", "গ্লুকোজ", "সেলুলোজ"],
    1,
  ),
  bq(
    2027,
    "Science",
    "কোন রঙের আলোর তরঙ্গদৈর্ঘ্য সবচেয়ে বেশি?",
    ["বেগুনি", "নীল", "সবুজ", "লাল"],
    3,
  ),
  bq(
    2028,
    "Science",
    "পৃথিবীতে প্রথম জীবনের উদ্ভব হয়েছিল কোথায়?",
    ["স্থলে", "সমুদ্রে", "আকাশে", "পর্বতে"],
    1,
    Difficulty.hard,
  ),
  bq(
    2029,
    "Science",
    "মস্তিষ্কে কোন ধরনের তরঙ্গ পাওয়া যায়?",
    ["আলোক তরঙ্গ", "বৈদ্যুতিক তরঙ্গ", "শব্দ তরঙ্গ", "রেডিও তরঙ্গ"],
    1,
    Difficulty.hard,
  ),
  bq(
    2030,
    "Science",
    "গাছের পাতা সবুজ কেন?",
    ["ক্লোরোফিলের কারণে", "পানির কারণে", "সূর্যালোকের কারণে", "মাটির কারণে"],
    0,
    Difficulty.easy,
  ),

  // ===== History - Bengali =====
  bq(
    3001,
    "History",
    "বাংলাদেশের স্বাধীনতা দিবস কত তারিখে?",
    ["১৬ ডিসেম্বর", "২৬ মার্চ", "১৫ আগস্ট", "২১ ফেব্রুয়ারি"],
    1,
    Difficulty.easy,
  ),
  bq(
    3002,
    "History",
    "বঙ্গবন্ধু শেখ মুজিবুর রহমানের জন্ম কত সালে?",
    ["১৯১৮", "১৯২০", "১৯২২", "১৯২৪"],
    1,
    Difficulty.easy,
  ),
  bq(
    3003,
    "History",
    "ভাষা আন্দোলন কত সালে হয়েছিল?",
    ["১৯৫০", "১৯৫২", "১৯৫৪", "১৯৫৬"],
    1,
    Difficulty.easy,
  ),
  bq(
    3004,
    "History",
    "মোগল সাম্রাজ্যের প্রতিষ্ঠাতা কে?",
    ["আকবর", "বাবর", "হুমায়ুন", "জাহাঙ্গীর"],
    1,
  ),
  bq(
    3005,
    "History",
    "প্রথম বিশ্বযুদ্ধ কত সালে শুরু হয়েছিল?",
    ["১৯১২", "১৯১৪", "১৯১৬", "১৯১৮"],
    1,
    Difficulty.easy,
  ),
  bq(
    3006,
    "History",
    "ব্রিটিশরা ভারত ছেড়ে যায় কত সালে?",
    ["১৯৪৫", "১৯৪৬", "১৯৪৭", "১৯৪৮"],
    2,
  ),
  bq(
    3007,
    "History",
    "বাংলাদেশের প্রথম রাষ্ট্রপতি কে ছিলেন?",
    ["শেখ মুজিবুর রহমান", "তাজউদ্দীন আহমদ", "সৈয়দ নজরুল ইসলাম", "জিয়াউর রহমান"],
    0,
  ),
  bq(
    3008,
    "History",
    "বিজয় দিবস কত তারিখে?",
    ["১৬ ডিসেম্বর", "২৬ মার্চ", "১৫ আগস্ট", "৭ মার্চ"],
    0,
    Difficulty.easy,
  ),
  bq(
    3009,
    "History",
    "তাজমহল কোথায় অবস্থিত?",
    ["দিল্লি", "আগ্রা", "জয়পুর", "মুম্বাই"],
    1,
    Difficulty.easy,
  ),
  bq(
    3010,
    "History",
    "দ্বিতীয় বিশ্বযুদ্ধ কত সালে শেষ হয়?",
    ["১৯৪৩", "১৯৪৪", "১৯৪৫", "১৯৪৬"],
    2,
    Difficulty.easy,
  ),
  bq(
    3011,
    "History",
    "আমেরিকার স্বাধীনতা ঘোষণাপত্র কোন তারিখে স্বাক্ষরিত হয়?",
    ["৪ জুলাই ১৭৭৬", "৪ জুলাই ১৭৮৬", "৪ জুলাই ১৭৯৬", "৪ জুলাই ১৮০০"],
    0,
  ),
  bq(
    3012,
    "History",
    "বার্লিন প্রাচীর কত সালে পড়ে?",
    ["১৯৮৭", "১৯৮৮", "১৯৮৯", "১৯৯০"],
    2,
  ),
  bq(
    3013,
    "History",
    "ভারতের প্রথম প্রধানমন্ত্রী কে ছিলেন?",
    ["মহাত্মা গান্ধী", "সুভাষচন্দ্র বসু", "জওহরলাল নেহরু", "বল্লভভাই প্যাটেল"],
    2,
    Difficulty.easy,
  ),
  bq(
    3014,
    "History",
    "বাংলাদেশের সংবিধান কত সালে গৃহীত হয়?",
    ["১৯৭১", "১৯৭২", "১৯৭৩", "১৯৭৪"],
    1,
  ),
  bq(
    3015,
    "History",
    "সিপাহী বিদ্রোহ কত সালে হয়েছিল?",
    ["১৮৫৫", "১৮৫৭", "১৮৫৯", "১৮৬১"],
    1,
  ),
  bq(
    3016,
    "History",
    "ফরাসি বিপ্লব কত সালে শুরু হয়?",
    ["১৭৮৭", "১৭৮৯", "১৭৯১", "১৭৯৩"],
    1,
  ),
  bq(
    3017,
    "History",
    "সম্রাট অশোক কোন রাজবংশের ছিলেন?",
    ["গুপ্ত", "মৌর্য", "কুষাণ", "পাল"],
    1,
  ),
  bq(
    3018,
    "History",
    "মুক্তিযুদ্ধে মুক্তিবাহিনীর সর্বাধিনায়ক কে ছিলেন?",
    ["শেখ মুজিবুর রহমান", "জেনারেল ওসমানী", "জিয়াউর রহমান", "তাজউদ্দীন আহমদ"],
    1,
  ),
  bq(
    3019,
    "History",
    "বাংলাদেশের স্বাধীনতার ঘোষণা দেন কে?",
    ["তাজউদ্দীন আহমদ", "শেখ মুজিবুর রহমান", "জিয়াউর রহমান", "সৈয়দ নজরুল ইসলাম"],
    1,
  ),
  bq(
    3020,
    "History",
    "প্রাচীন সভ্যতার মধ্যে কোনটি সবচেয়ে পুরানো?",
    ["গ্রিক সভ্যতা", "রোমান সভ্যতা", "মেসোপটেমিয়া সভ্যতা", "মিসরীয় সভ্যতা"],
    2,
    Difficulty.hard,
  ),

  // ===== Sports - Bengali =====
  bq(
    4001,
    "Sports",
    "ক্রিকেটে একটি ওভারে কতটি বল থাকে?",
    ["৪টি", "৫টি", "৬টি", "৮টি"],
    2,
    Difficulty.easy,
  ),
  bq(
    4002,
    "Sports",
    "ফুটবল বিশ্বকাপ কত বছর পরপর অনুষ্ঠিত হয়?",
    ["২ বছর", "৩ বছর", "৪ বছর", "৫ বছর"],
    2,
    Difficulty.easy,
  ),
  bq(
    4003,
    "Sports",
    "অলিম্পিক গেমস কত বছর পরপর হয়?",
    ["২ বছর", "৪ বছর", "৬ বছর", "৮ বছর"],
    1,
    Difficulty.easy,
  ),
  bq(
    4004,
    "Sports",
    "বাংলাদেশ ক্রিকেট দলের অধিনায়ক (২০২৪) কে?",
    ["সাকিব আল হাসান", "তামিম ইকবাল", "মাশরাফি বিন মুর্তজা", "নাজমুল হোসেন শান্ত"],
    3,
  ),
  bq(
    4005,
    "Sports",
    "টেনিসে সবচেয়ে বেশি গ্র্যান্ড স্ল্যাম জিতেছেন কে?",
    ["রজার ফেদেরার", "নোভাক জোকোভিচ", "রাফায়েল নাদাল", "পিট সাম্প্রাস"],
    1,
    Difficulty.hard,
  ),
  bq(
    4006,
    "Sports",
    "ফিফা বিশ্বকাপ ২০২২ কোন দেশ জিতেছে?",
    ["ফ্রান্স", "ব্রাজিল", "আর্জেন্টিনা", "জার্মানি"],
    2,
  ),
  bq(
    4007,
    "Sports",
    "ক্রিকেটে 'হ্যাটট্রিক' মানে কী?",
    ["তিনটি সিক্স", "তিনটি চার", "পরপর তিন বলে তিন উইকেট", "পরপর তিন বলে তিন রান"],
    2,
  ),
  bq(
    4008,
    "Sports",
    "বাংলাদেশের জাতীয় ক্রিকেট স্টেডিয়াম কোথায়?",
    ["মিরপুর স্টেডিয়াম", "বঙ্গবন্ধু জাতীয় স্টেডিয়াম", "চট্টগ্রাম স্টেডিয়াম", "সিলেট স্টেডিয়াম"],
    0,
  ),
  bq(
    4009,
    "Sports",
    "ফুটবলে একটি দলে কতজন খেলোয়াড় থাকে?",
    ["৯জন", "১০জন", "১১জন", "১২জন"],
    2,
    Difficulty.easy,
  ),
  bq(
    4010,
    "Sports",
    "অলিম্পিক রিং-এর সংখ্যা কত?",
    ["৪টি", "৫টি", "৬টি", "৭টি"],
    1,
    Difficulty.easy,
  ),
  bq(
    4011,
    "Sports",
    "বাস্কেটবল খেলার মাঠকে কী বলে?",
    ["পিচ", "কোর্ট", "ফিল্ড", "ট্র্যাক"],
    1,
    Difficulty.easy,
  ),
  bq(
    4012,
    "Sports",
    "বিশ্বের সবচেয়ে জনপ্রিয় খেলা কোনটি?",
    ["ক্রিকেট", "বাস্কেটবল", "ফুটবল", "টেনিস"],
    2,
    Difficulty.easy,
  ),
  bq(
    4013,
    "Sports",
    "সাকিব আল হাসান কোন ধরনের ক্রিকেটার?",
    ["শুধু ব্যাটার", "শুধু বোলার", "অলরাউন্ডার", "উইকেটকিপার"],
    2,
    Difficulty.easy,
  ),
  bq(
    4014,
    "Sports",
    "ম্যারাথন দৌড়ের দূরত্ব কত?",
    ["৪০ কিমি", "৪২.১৯৫ কিমি", "৪৫ কিমি", "৩৮ কিমি"],
    1,
  ),
  bq(
    4015,
    "Sports",
    "ব্যাডমিন্টনে শাটলকক কী দিয়ে তৈরি?",
    ["রাবার", "পালক", "প্লাস্টিক", "উপরের সবগুলো"],
    3,
  ),
  bq(
    4016,
    "Sports",
    "ভারতের সাবেক ক্রিকেট অধিনায়ক সচিন তেন্ডুলকারের আন্তর্জাতিক সেঞ্চুরি সংখ্যা?",
    ["৯৫টি", "১০০টি", "১০০+টি", "৮৫টি"],
    2,
    Difficulty.hard,
  ),
  bq(
    4017,
    "Sports",
    "টেনিসে কোন কোর্টে উইম্বলডন অনুষ্ঠিত হয়?",
    ["কাদামাটির কোর্ট", "হার্ড কোর্ট", "ঘাসের কোর্ট", "কার্পেটের কোর্ট"],
    2,
  ),
  bq(
    4018,
    "Sports",
    "ক্রিকেটে 'এলবিডব্লু' মানে কী?",
    [
      "লেফট বিফোর উইকেট",
      "লেগ বিফোর উইকেট",
      "লং বিফোর উইকেট",
      "লাইন বিফোর উইকেট",
    ],
    1,
  ),
  bq(
    4019,
    "Sports",
    "সর্বকালের সেরা ফুটবলার হিসেবে পেলে কোন দেশের?",
    ["আর্জেন্টিনা", "স্পেন", "ব্রাজিল", "পর্তুগাল"],
    2,
    Difficulty.easy,
  ),
  bq(
    4020,
    "Sports",
    "বাংলাদেশ প্রথম টেস্ট ম্যাচ খেলে কত সালে?",
    ["১৯৯৮", "২০০০", "২০০১", "২০০৩"],
    1,
  ),

  // ===== Math - Bengali =====
  bq(
    5001,
    "Math",
    "১ থেকে ১০০ পর্যন্ত সংখ্যার যোগফল কত?",
    ["৪৯৫০", "৫০০০", "৫০৫০", "৫১৫০"],
    2,
  ),
  bq(
    5002,
    "Math",
    "২৫ × ৪ = ?",
    ["৯০", "১০০", "১১০", "১২০"],
    1,
    Difficulty.easy,
  ),
  bq(5003, "Math", "√১৪৪ = ?", ["১০", "১২", "১৪", "১৬"], 1, Difficulty.easy),
  bq(
    5004,
    "Math",
    "একটি বৃত্তের ব্যাসার্ধ ৭ হলে ক্ষেত্রফল কত? (π = ২২/৭)",
    ["১৫৪", "১৪৪", "১৬৪", "১৩৪"],
    0,
  ),
  bq(
    5005,
    "Math",
    "১২ × ১২ = ?",
    ["১২৪", "১৩৪", "১৪৪", "১৫৪"],
    2,
    Difficulty.easy,
  ),
  bq(5006, "Math", "৩৬ ÷ ৬ = ?", ["৪", "৫", "৬", "৭"], 2, Difficulty.easy),
  bq(5007, "Math", "৫! (৫ ফ্যাক্টরিয়াল) = ?", ["১০০", "১১০", "১২০", "১৩০"], 2),
  bq(
    5008,
    "Math",
    "দুটি সংখ্যার LCM ৩৬ এবং HCF ৬ হলে, তাদের গুণফল কত?",
    ["২১৬", "২০০", "১৮০", "২৪০"],
    0,
    Difficulty.hard,
  ),
  bq(
    5009,
    "Math",
    "একটি ত্রিভুজের কোণের সমষ্টি কত?",
    ["৯০°", "১৮০°", "২৭০°", "৩৬০°"],
    1,
    Difficulty.easy,
  ),
  bq(5010, "Math", "২ + ২ × ২ = ?", ["৬", "৮", "৪", "১০"], 0),
  bq(
    5011,
    "Math",
    "১০০ এর ১৫% কত?",
    ["১০", "১৫", "২০", "২৫"],
    1,
    Difficulty.easy,
  ),
  bq(
    5012,
    "Math",
    "৩x = ২৭ হলে x = ?",
    ["৬", "৭", "৮", "৯"],
    3,
    Difficulty.easy,
  ),
  bq(
    5013,
    "Math",
    "একটি আয়তক্ষেত্রের দৈর্ঘ্য ৮ এবং প্রস্থ ৫ হলে ক্ষেত্রফল কত?",
    ["৩০", "৩৫", "৪০", "৪৫"],
    2,
    Difficulty.easy,
  ),
  bq(5014, "Math", "৫² + ১২² = ?", ["১৪৪", "১৬৯", "১৯৬", "২২৫"], 1),
  bq(
    5015,
    "Math",
    "কোনটি মৌলিক সংখ্যা?",
    ["৯", "১৫", "১৭", "২১"],
    2,
    Difficulty.easy,
  ),

  // ===== Geography - Bengali =====
  bq(
    6001,
    "Geography",
    "বাংলাদেশের সবচেয়ে বড় নদী কোনটি?",
    ["যমুনা", "পদ্মা", "মেঘনা", "ব্রহ্মপুত্র"],
    1,
  ),
  bq(
    6002,
    "Geography",
    "বিশ্বের দীর্ঘতম পর্বতমালা কোনটি?",
    ["হিমালয়", "রকি মাউন্টেন", "আন্দিজ", "আল্পস"],
    2,
  ),
  bq(
    6003,
    "Geography",
    "বাংলাদেশের সবচেয়ে বড় দ্বীপ কোনটি?",
    ["সন্দ্বীপ", "ভোলা", "হাতিয়া", "কুতুবদিয়া"],
    1,
    Difficulty.easy,
  ),
  bq(
    6004,
    "Geography",
    "পৃথিবীর সবচেয়ে বড় ব-দ্বীপ কোনটি?",
    ["নীলনদ ডেল্টা", "মেকং ডেল্টা", "গঙ্গা-ব্রহ্মপুত্র ডেল্টা", "মিসিসিপি ডেল্টা"],
    2,
    Difficulty.hard,
  ),
  bq(
    6005,
    "Geography",
    "আফ্রিকার সর্বোচ্চ পর্বতশৃঙ্গ কোনটি?",
    ["মাউন্ট কেনিয়া", "কিলিমানজারো", "রাস দাশান", "দ্রাকেন্সবার্গ"],
    1,
  ),
  bq(
    6006,
    "Geography",
    "কোন মহাদেশে সবচেয়ে বেশি দেশ আছে?",
    ["এশিয়া", "ইউরোপ", "আফ্রিকা", "আমেরিকা"],
    2,
  ),
  bq(
    6007,
    "Geography",
    "ভারতের রাজধানী কোথায়?",
    ["মুম্বাই", "কলকাতা", "নতুন দিল্লি", "চেন্নাই"],
    2,
    Difficulty.easy,
  ),
  bq(
    6008,
    "Geography",
    "বিশ্বের কোন দেশে সূর্য কখনো অস্ত যায় না (গ্রীষ্মে)?",
    ["ডেনমার্ক", "নরওয়ে", "ফিনল্যান্ড", "সুইডেন"],
    1,
  ),
  bq(
    6009,
    "Geography",
    "মধ্যপ্রাচ্যের কোন দেশটি তেলে সবচেয়ে সমৃদ্ধ?",
    ["ইরান", "ইরাক", "সৌদি আরব", "কুয়েত"],
    2,
    Difficulty.easy,
  ),
  bq(
    6010,
    "Geography",
    "বাংলাদেশের সাথে কতটি দেশের সীমানা আছে?",
    ["১টি", "২টি", "৩টি", "৪টি"],
    1,
    Difficulty.easy,
  ),

  // ===== Technology - Bengali =====
  bq(
    7001,
    "Technology",
    "WWW-এর পূর্ণরূপ কী?",
    ["World Wide Web", "World Web Wide", "Wide World Web", "Web World Wide"],
    0,
    Difficulty.easy,
  ),
  bq(
    7002,
    "Technology",
    "CPU-এর পূর্ণরূপ কী?",
    [
      "Central Processing Unit",
      "Computer Processing Unit",
      "Control Processing Unit",
      "Core Processing Unit",
    ],
    0,
    Difficulty.easy,
  ),
  bq(
    7003,
    "Technology",
    "HTML-এর পূর্ণরূপ কী?",
    [
      "Hyper Text Markup Language",
      "High Text Making Language",
      "Hyper Transfer Markup Language",
      "None",
    ],
    0,
  ),
  bq(
    7004,
    "Technology",
    "কোন সংস্থা ইন্টারনেট পরিচালনা করে?",
    ["গুগল", "মেটা", "আইকান (ICANN)", "মাইক্রোসফট"],
    2,
    Difficulty.hard,
  ),
  bq(
    7005,
    "Technology",
    "প্রথম কম্পিউটার প্রোগ্রামার কে?",
    ["চার্লস ব্যাবেজ", "অ্যাডা লাভলেস", "অ্যালান টুরিং", "গ্রেস হপার"],
    1,
    Difficulty.hard,
  ),
  bq(
    7006,
    "Technology",
    "স্মার্টফোনের অপারেটিং সিস্টেম হিসেবে Android তৈরি করেছে কে?",
    ["অ্যাপল", "মাইক্রোসফট", "গুগল", "স্যামসাং"],
    2,
    Difficulty.easy,
  ),
  bq(
    7007,
    "Technology",
    "ফেসবুকের প্রতিষ্ঠাতা কে?",
    ["জেফ বেজোস", "ইলন মাস্ক", "মার্ক জাকারবার্গ", "স্টিভ জবস"],
    2,
    Difficulty.easy,
  ),
  bq(
    7008,
    "Technology",
    "১ গিগাবাইট = কত মেগাবাইট?",
    ["৫১২ MB", "৮০০ MB", "১০২৪ MB", "২০৪৮ MB"],
    2,
    Difficulty.easy,
  ),
  bq(
    7009,
    "Technology",
    "ইন্টারনেটে ডেটা পাঠানোর প্রোটোকল কোনটি?",
    ["HTTP", "TCP/IP", "FTP", "SMTP"],
    1,
    Difficulty.hard,
  ),
  bq(
    7010,
    "Technology",
    "কোন কোম্পানি iPhone তৈরি করে?",
    ["স্যামসাং", "অ্যাপল", "সনি", "নোকিয়া"],
    1,
    Difficulty.easy,
  ),

  // ===== Literature - Bengali =====
  bq(
    8001,
    "Literature",
    "রবীন্দ্রনাথ ঠাকুর নোবেল পুরস্কার পান কত সালে?",
    ["১৯১১", "১৯১২", "১৯১৩", "১৯১৪"],
    2,
    Difficulty.easy,
  ),
  bq(
    8002,
    "Literature",
    "'আমার সোনার বাংলা' গানটি কে লিখেছেন?",
    ["কাজী নজরুল ইসলাম", "রবীন্দ্রনাথ ঠাকুর", "জীবনানন্দ দাশ", "সুকান্ত ভট্টাচার্য"],
    1,
    Difficulty.easy,
  ),
  bq(
    8003,
    "Literature",
    "'পদ্মাবতী' কাব্যের রচয়িতা কে?",
    ["রবীন্দ্রনাথ ঠাকুর", "মাইকেল মধুসূদন দত্ত", "আলাওল", "কাজী নজরুল ইসলাম"],
    2,
  ),
  bq(
    8004,
    "Literature",
    "বাংলা সাহিত্যের প্রথম উপন্যাস কোনটি?",
    ["আনন্দমঠ", "দুর্গেশনন্দিনী", "বিষবৃক্ষ", "কপালকুণ্ডলা"],
    1,
  ),
  bq(
    8005,
    "Literature",
    "কাজী নজরুল ইসলামকে কী বলা হয়?",
    ["মহাকবি", "বিদ্রোহী কবি", "পল্লীকবি", "রাষ্ট্রকবি"],
    1,
    Difficulty.easy,
  ),
  bq(
    8006,
    "Literature",
    "শেক্সপিয়ারের বিখ্যাত নাটক 'হ্যামলেট' কোন দেশের গল্প?",
    ["ইংল্যান্ড", "ফ্রান্স", "ডেনমার্ক", "ইতালি"],
    2,
  ),
  bq(
    8007,
    "Literature",
    "'গীতাঞ্জলি' কার রচনা?",
    ["রবীন্দ্রনাথ ঠাকুর", "কাজী নজরুল ইসলাম", "মাইকেল মধুসূদন দত্ত", "বঙ্কিমচন্দ্র চট্টোপাধ্যায়"],
    0,
    Difficulty.easy,
  ),
  bq(
    8008,
    "Literature",
    "জসীমউদ্দীনকে কী কবি বলা হয়?",
    ["বিদ্রোহী কবি", "পল্লীকবি", "রাষ্ট্রকবি", "মহাকবি"],
    1,
    Difficulty.easy,
  ),
  bq(
    8009,
    "Literature",
    "'মেঘনাদবধ কাব্য' কে লিখেছেন?",
    ["রবীন্দ্রনাথ ঠাকুর", "মাইকেল মধুসূদন দত্ত", "কাজী নজরুল ইসলাম", "জীবনানন্দ দাশ"],
    1,
  ),
  bq(
    8010,
    "Literature",
    "'বিষাদসিন্ধু' উপন্যাসের লেখক কে?",
    [
      "রবীন্দ্রনাথ ঠাকুর",
      "বঙ্কিমচন্দ্র চট্টোপাধ্যায়",
      "মীর মশাররফ হোসেন",
      "শরৎচন্দ্র চট্টোপাধ্যায়",
    ],
    2,
  ),

  // ===== General Knowledge - English =====
  eq(
    9001,
    "General Knowledge",
    "What is the capital of Bangladesh?",
    ["Chittagong", "Sylhet", "Dhaka", "Rajshahi"],
    2,
    Difficulty.easy,
  ),
  eq(
    9002,
    "General Knowledge",
    "What is the largest ocean on Earth?",
    ["Atlantic", "Indian", "Pacific", "Arctic"],
    2,
    Difficulty.easy,
  ),
  eq(
    9003,
    "General Knowledge",
    "How many continents are there on Earth?",
    ["5", "6", "7", "8"],
    2,
    Difficulty.easy,
  ),
  eq(
    9004,
    "General Knowledge",
    "Which planet is known as the Red Planet?",
    ["Venus", "Jupiter", "Saturn", "Mars"],
    3,
    Difficulty.easy,
  ),
  eq(
    9005,
    "General Knowledge",
    "What is the national flower of Bangladesh?",
    ["Rose", "Shapla (Water Lily)", "Jasmine", "Lotus"],
    1,
    Difficulty.easy,
  ),
  eq(
    9006,
    "General Knowledge",
    "How many days are in a leap year?",
    ["364", "365", "366", "367"],
    2,
    Difficulty.easy,
  ),
  eq(
    9007,
    "General Knowledge",
    "What is the smallest country in the world?",
    ["Monaco", "San Marino", "Liechtenstein", "Vatican City"],
    3,
  ),
  eq(
    9008,
    "General Knowledge",
    "How many bones are in the adult human body?",
    ["204", "206", "208", "210"],
    1,
  ),
  eq(
    9009,
    "General Knowledge",
    "Which country is the largest in the world by area?",
    ["China", "Canada", "Russia", "USA"],
    2,
    Difficulty.easy,
  ),
  eq(
    9010,
    "General Knowledge",
    "What is the currency of the United Kingdom?",
    ["Euro", "Dollar", "Pound Sterling", "Franc"],
    2,
    Difficulty.easy,
  ),
  eq(
    9011,
    "General Knowledge",
    "How many colors are in a rainbow?",
    ["5", "6", "7", "8"],
    2,
    Difficulty.easy,
  ),
  eq(
    9012,
    "General Knowledge",
    "Which animal is known as the King of the jungle?",
    ["Tiger", "Lion", "Elephant", "Leopard"],
    1,
    Difficulty.easy,
  ),
  eq(
    9013,
    "General Knowledge",
    "What is the tallest mountain in the world?",
    ["K2", "Kangchenjunga", "Mount Everest", "Lhotse"],
    2,
    Difficulty.easy,
  ),
  eq(
    9014,
    "General Knowledge",
    "How many hours are in a day?",
    ["12", "18", "24", "36"],
    2,
    Difficulty.easy,
  ),
  eq(
    9015,
    "General Knowledge",
    "Which planet is closest to the Sun?",
    ["Venus", "Earth", "Mercury", "Mars"],
    2,
    Difficulty.easy,
  ),
  eq(
    9016,
    "General Knowledge",
    "What is the capital of France?",
    ["Lyon", "Marseille", "Paris", "Nice"],
    2,
    Difficulty.easy,
  ),
  eq(
    9017,
    "General Knowledge",
    "How many sides does a hexagon have?",
    ["5", "6", "7", "8"],
    1,
    Difficulty.easy,
  ),
  eq(
    9018,
    "General Knowledge",
    "What is the largest desert in the world?",
    ["Gobi", "Sahara", "Antarctica", "Arabian"],
    2,
    Difficulty.hard,
  ),
  eq(
    9019,
    "General Knowledge",
    "What language is most widely spoken in the world?",
    ["English", "Spanish", "Mandarin Chinese", "Hindi"],
    2,
  ),
  eq(
    9020,
    "General Knowledge",
    "What is the capital of Japan?",
    ["Osaka", "Kyoto", "Tokyo", "Hiroshima"],
    2,
    Difficulty.easy,
  ),
  eq(
    9021,
    "General Knowledge",
    "Which is the longest river in the world?",
    ["Amazon", "Nile", "Yangtze", "Mississippi"],
    1,
    Difficulty.easy,
  ),
  eq(
    9022,
    "General Knowledge",
    "How many minutes are in an hour?",
    ["30", "45", "60", "90"],
    2,
    Difficulty.easy,
  ),
  eq(
    9023,
    "General Knowledge",
    "What is the capital of Australia?",
    ["Sydney", "Melbourne", "Brisbane", "Canberra"],
    3,
  ),
  eq(
    9024,
    "General Knowledge",
    "Who wrote 'Romeo and Juliet'?",
    ["Charles Dickens", "William Shakespeare", "Jane Austen", "Mark Twain"],
    1,
    Difficulty.easy,
  ),
  eq(
    9025,
    "General Knowledge",
    "How many stars are on the American flag?",
    ["48", "50", "52", "54"],
    1,
  ),
  eq(
    9026,
    "General Knowledge",
    "What is the capital of Canada?",
    ["Toronto", "Vancouver", "Montreal", "Ottawa"],
    3,
  ),
  eq(
    9027,
    "General Knowledge",
    "Which gas do plants absorb during photosynthesis?",
    ["Oxygen", "Nitrogen", "Carbon Dioxide", "Hydrogen"],
    2,
    Difficulty.easy,
  ),
  eq(
    9028,
    "General Knowledge",
    "How many legs does a spider have?",
    ["6", "8", "10", "12"],
    1,
    Difficulty.easy,
  ),
  eq(
    9029,
    "General Knowledge",
    "What is the capital of China?",
    ["Shanghai", "Beijing", "Guangzhou", "Chengdu"],
    1,
    Difficulty.easy,
  ),
  eq(
    9030,
    "General Knowledge",
    "Which metal is liquid at room temperature?",
    ["Iron", "Gold", "Mercury", "Silver"],
    2,
  ),

  // ===== Science - English =====
  eq(
    10001,
    "Science",
    "What is the chemical formula for water?",
    ["CO₂", "H₂O", "NaCl", "O₂"],
    1,
    Difficulty.easy,
  ),
  eq(
    10002,
    "Science",
    "What is the speed of light?",
    ["200,000 km/s", "300,000 km/s", "400,000 km/s", "150,000 km/s"],
    1,
    Difficulty.easy,
  ),
  eq(
    10003,
    "Science",
    "Which gas makes up most of Earth's atmosphere?",
    ["Oxygen", "Carbon Dioxide", "Nitrogen", "Helium"],
    2,
    Difficulty.easy,
  ),
  eq(
    10004,
    "Science",
    "How many chambers does the human heart have?",
    ["2", "3", "4", "5"],
    2,
    Difficulty.easy,
  ),
  eq(
    10005,
    "Science",
    "What is the powerhouse of the cell?",
    ["Nucleus", "Ribosome", "Mitochondria", "Golgi apparatus"],
    2,
  ),
  eq(
    10006,
    "Science",
    "How long does it take sunlight to reach Earth?",
    ["5 minutes", "8 minutes", "12 minutes", "15 minutes"],
    1,
  ),
  eq(
    10007,
    "Science",
    "What is the atomic number of carbon?",
    ["4", "6", "8", "12"],
    1,
  ),
  eq(
    10008,
    "Science",
    "What is DNA?",
    ["A protein", "A lipid", "A nucleic acid", "A carbohydrate"],
    2,
    Difficulty.hard,
  ),
  eq(
    10009,
    "Science",
    "What is the largest planet in our solar system?",
    ["Saturn", "Neptune", "Jupiter", "Uranus"],
    2,
    Difficulty.easy,
  ),
  eq(
    10010,
    "Science",
    "What is the chemical symbol for gold?",
    ["Go", "Gd", "Au", "Ag"],
    2,
  ),
  eq(
    10011,
    "Science",
    "How many teeth does an adult human have?",
    ["28", "30", "32", "34"],
    2,
  ),
  eq(
    10012,
    "Science",
    "What force keeps planets in orbit around the Sun?",
    ["Magnetism", "Electricity", "Gravity", "Friction"],
    2,
    Difficulty.easy,
  ),
  eq(
    10013,
    "Science",
    "What is the boiling point of water at sea level?",
    ["90°C", "95°C", "100°C", "105°C"],
    2,
    Difficulty.easy,
  ),
  eq(
    10014,
    "Science",
    "What is the smallest unit of life?",
    ["Organ", "Tissue", "Cell", "Atom"],
    2,
    Difficulty.easy,
  ),
  eq(
    10015,
    "Science",
    "Which vitamin is produced when the skin is exposed to sunlight?",
    ["Vitamin A", "Vitamin B", "Vitamin C", "Vitamin D"],
    3,
  ),
  eq(
    10016,
    "Science",
    "What is the hardest natural substance on Earth?",
    ["Gold", "Platinum", "Diamond", "Quartz"],
    2,
    Difficulty.easy,
  ),
  eq(
    10017,
    "Science",
    "How many chromosomes do humans have?",
    ["23", "44", "46", "48"],
    2,
    Difficulty.hard,
  ),
  eq(
    10018,
    "Science",
    "What type of energy does the Sun produce?",
    [
      "Chemical energy",
      "Nuclear energy",
      "Mechanical energy",
      "Electrical energy",
    ],
    1,
    Difficulty.hard,
  ),
  eq(
    10019,
    "Science",
    "What is the most abundant element in the universe?",
    ["Oxygen", "Carbon", "Hydrogen", "Helium"],
    2,
    Difficulty.hard,
  ),
  eq(
    10020,
    "Science",
    "What organ produces insulin in the human body?",
    ["Liver", "Kidney", "Pancreas", "Stomach"],
    2,
  ),

  // ===== History - English =====
  eq(
    11001,
    "History",
    "When did Bangladesh gain independence?",
    ["1969", "1970", "1971", "1972"],
    2,
    Difficulty.easy,
  ),
  eq(
    11002,
    "History",
    "Who was the first President of the United States?",
    [
      "Thomas Jefferson",
      "John Adams",
      "George Washington",
      "Benjamin Franklin",
    ],
    2,
    Difficulty.easy,
  ),
  eq(
    11003,
    "History",
    "In which year did World War II end?",
    ["1943", "1944", "1945", "1946"],
    2,
    Difficulty.easy,
  ),
  eq(
    11004,
    "History",
    "Who was the founder of the Mughal Empire?",
    ["Akbar", "Babur", "Humayun", "Jahangir"],
    1,
  ),
  eq(
    11005,
    "History",
    "The Language Movement in Bangladesh occurred in which year?",
    ["1950", "1952", "1954", "1956"],
    1,
    Difficulty.easy,
  ),
  eq(
    11006,
    "History",
    "Which country was the first to give women the right to vote?",
    ["USA", "UK", "New Zealand", "France"],
    2,
  ),
  eq(
    11007,
    "History",
    "Who built the Taj Mahal?",
    ["Akbar", "Shah Jahan", "Aurangzeb", "Jahangir"],
    1,
  ),
  eq(
    11008,
    "History",
    "When did the Berlin Wall fall?",
    ["1987", "1988", "1989", "1990"],
    2,
  ),
  eq(
    11009,
    "History",
    "Who was the first man to walk on the Moon?",
    ["Buzz Aldrin", "Neil Armstrong", "Yuri Gagarin", "John Glenn"],
    1,
    Difficulty.easy,
  ),
  eq(
    11010,
    "History",
    "In which year did the French Revolution begin?",
    ["1787", "1789", "1791", "1793"],
    1,
  ),
  eq(
    11011,
    "History",
    "Who wrote the Declaration of Independence?",
    ["George Washington", "John Adams", "Thomas Jefferson", "James Madison"],
    2,
  ),
  eq(
    11012,
    "History",
    "In which year did India gain independence?",
    ["1945", "1946", "1947", "1948"],
    2,
    Difficulty.easy,
  ),
  eq(
    11013,
    "History",
    "Who was Napoleon Bonaparte?",
    ["French Emperor", "British King", "Russian Tsar", "German Chancellor"],
    0,
  ),
  eq(
    11014,
    "History",
    "Which empire was known as the largest in history?",
    ["Roman Empire", "British Empire", "Mongol Empire", "Ottoman Empire"],
    1,
    Difficulty.hard,
  ),
  eq(
    11015,
    "History",
    "In which year was the United Nations founded?",
    ["1943", "1944", "1945", "1946"],
    2,
  ),
  eq(
    11016,
    "History",
    "Who invented the telephone?",
    [
      "Thomas Edison",
      "Alexander Graham Bell",
      "Nikola Tesla",
      "Guglielmo Marconi",
    ],
    1,
    Difficulty.easy,
  ),
  eq(
    11017,
    "History",
    "Which war was fought between the North and South of the USA?",
    ["Revolutionary War", "Civil War", "World War I", "Spanish-American War"],
    1,
    Difficulty.easy,
  ),
  eq(
    11018,
    "History",
    "In which city were the first modern Olympics held?",
    ["Paris", "London", "Athens", "Rome"],
    2,
  ),
  eq(
    11019,
    "History",
    "Who was the first woman to win a Nobel Prize?",
    ["Malala Yousafzai", "Mother Teresa", "Marie Curie", "Aung San Suu Kyi"],
    2,
  ),
  eq(
    11020,
    "History",
    "What year did the Titanic sink?",
    ["1910", "1912", "1914", "1916"],
    1,
    Difficulty.easy,
  ),

  // ===== Sports - English =====
  eq(
    12001,
    "Sports",
    "How many balls are in an over in cricket?",
    ["4", "5", "6", "8"],
    2,
    Difficulty.easy,
  ),
  eq(
    12002,
    "Sports",
    "How often is the FIFA World Cup held?",
    ["Every 2 years", "Every 3 years", "Every 4 years", "Every 5 years"],
    2,
    Difficulty.easy,
  ),
  eq(
    12003,
    "Sports",
    "How many players are in a football (soccer) team?",
    ["9", "10", "11", "12"],
    2,
    Difficulty.easy,
  ),
  eq(
    12004,
    "Sports",
    "Who won the FIFA World Cup 2022?",
    ["France", "Brazil", "Argentina", "Germany"],
    2,
  ),
  eq(
    12005,
    "Sports",
    "How many Olympic rings are there?",
    ["4", "5", "6", "7"],
    1,
    Difficulty.easy,
  ),
  eq(
    12006,
    "Sports",
    "Which sport uses a shuttlecock?",
    ["Tennis", "Squash", "Badminton", "Table Tennis"],
    2,
    Difficulty.easy,
  ),
  eq(
    12007,
    "Sports",
    "Who holds the most Grand Slam titles in tennis?",
    ["Roger Federer", "Novak Djokovic", "Rafael Nadal", "Pete Sampras"],
    1,
    Difficulty.hard,
  ),
  eq(
    12008,
    "Sports",
    "How long is a standard marathon race?",
    ["40 km", "42.195 km", "45 km", "38 km"],
    1,
  ),
  eq(
    12009,
    "Sports",
    "How many players are on a basketball team on the court?",
    ["4", "5", "6", "7"],
    1,
    Difficulty.easy,
  ),
  eq(
    12010,
    "Sports",
    "What sport is played at Wimbledon?",
    ["Badminton", "Squash", "Tennis", "Table Tennis"],
    2,
    Difficulty.easy,
  ),
  eq(
    12011,
    "Sports",
    "Who is considered the greatest basketball player of all time?",
    ["LeBron James", "Kobe Bryant", "Michael Jordan", "Shaquille O'Neal"],
    2,
  ),
  eq(
    12012,
    "Sports",
    "How many holes are in a standard golf course?",
    ["9", "12", "18", "24"],
    2,
    Difficulty.easy,
  ),
  eq(
    12013,
    "Sports",
    "What country has won the most FIFA World Cups?",
    ["Argentina", "Germany", "Italy", "Brazil"],
    3,
  ),
  eq(
    12014,
    "Sports",
    "In boxing, how many rounds is a world title fight?",
    ["10", "12", "15", "8"],
    1,
  ),
  eq(
    12015,
    "Sports",
    "Which country hosted the 2020 (2021) Summer Olympics?",
    ["China", "Brazil", "Japan", "UK"],
    2,
  ),

  // ===== Math - English =====
  eq(
    13001,
    "Math",
    "What is 15% of 200?",
    ["25", "30", "35", "40"],
    1,
    Difficulty.easy,
  ),
  eq(
    13002,
    "Math",
    "What is the square root of 144?",
    ["10", "12", "14", "16"],
    1,
    Difficulty.easy,
  ),
  eq(
    13003,
    "Math",
    "What is 7 × 8?",
    ["48", "54", "56", "64"],
    2,
    Difficulty.easy,
  ),
  eq(
    13004,
    "Math",
    "What is π (Pi) approximately equal to?",
    ["2.14", "3.14", "4.14", "3.41"],
    1,
    Difficulty.easy,
  ),
  eq(13005, "Math", "What is 2⁸?", ["128", "256", "512", "64"], 1),
  eq(
    13006,
    "Math",
    "How many degrees are in a triangle?",
    ["90°", "180°", "270°", "360°"],
    1,
    Difficulty.easy,
  ),
  eq(
    13007,
    "Math",
    "What is the area of a circle with radius 5? (use π=3.14)",
    ["78.5", "75.0", "80.0", "70.5"],
    0,
  ),
  eq(
    13008,
    "Math",
    "What is 12²?",
    ["124", "134", "144", "154"],
    2,
    Difficulty.easy,
  ),
  eq(
    13009,
    "Math",
    "What is 50% of 80?",
    ["30", "35", "40", "45"],
    2,
    Difficulty.easy,
  ),
  eq(
    13010,
    "Math",
    "What is the next prime number after 7?",
    ["8", "9", "10", "11"],
    3,
    Difficulty.easy,
  ),
  eq(
    13011,
    "Math",
    "If x + 5 = 12, what is x?",
    ["5", "6", "7", "8"],
    2,
    Difficulty.easy,
  ),
  eq(13012, "Math", "What is 1000 ÷ 25?", ["30", "35", "40", "45"], 2),
  eq(
    13013,
    "Math",
    "What is the perimeter of a square with side 6?",
    ["18", "24", "30", "36"],
    1,
    Difficulty.easy,
  ),
  eq(
    13014,
    "Math",
    "What is 5! (5 factorial)?",
    ["100", "110", "120", "130"],
    2,
  ),
  eq(
    13015,
    "Math",
    "What is the value of 0³?",
    ["0", "1", "3", "undefined"],
    0,
    Difficulty.easy,
  ),

  // ===== Technology - English =====
  eq(
    14001,
    "Technology",
    "What does CPU stand for?",
    [
      "Central Processing Unit",
      "Computer Processing Unit",
      "Control Processing Unit",
      "Core Processing Unit",
    ],
    0,
    Difficulty.easy,
  ),
  eq(
    14002,
    "Technology",
    "Which company created the Android operating system?",
    ["Apple", "Microsoft", "Google", "Samsung"],
    2,
    Difficulty.easy,
  ),
  eq(
    14003,
    "Technology",
    "What does HTML stand for?",
    [
      "Hyper Text Markup Language",
      "High Text Making Language",
      "Hyper Transfer Markup Language",
      "None",
    ],
    0,
  ),
  eq(
    14004,
    "Technology",
    "Who is the founder of Microsoft?",
    ["Steve Jobs", "Elon Musk", "Bill Gates", "Jeff Bezos"],
    2,
    Difficulty.easy,
  ),
  eq(
    14005,
    "Technology",
    "What is the most popular programming language?",
    ["Java", "C++", "Python", "JavaScript"],
    3,
  ),
  eq(
    14006,
    "Technology",
    "What does RAM stand for?",
    [
      "Read Access Memory",
      "Random Access Memory",
      "Rapid Access Memory",
      "Real Access Memory",
    ],
    1,
    Difficulty.easy,
  ),
  eq(
    14007,
    "Technology",
    "Which company makes the iPhone?",
    ["Samsung", "Apple", "Sony", "Nokia"],
    1,
    Difficulty.easy,
  ),
  eq(
    14008,
    "Technology",
    "What is 1 Terabyte equal to?",
    ["512 GB", "1000 GB", "1024 GB", "2048 GB"],
    2,
  ),
  eq(
    14009,
    "Technology",
    "Who invented the World Wide Web?",
    ["Bill Gates", "Tim Berners-Lee", "Steve Jobs", "Mark Zuckerberg"],
    1,
  ),
  eq(
    14010,
    "Technology",
    "What social media platform has the most monthly users?",
    ["Instagram", "Twitter", "Facebook", "TikTok"],
    2,
  ),
];

// ===== Question Pool Management (No-Repeat System) =====
const SEEN_KEY = "quiz_seen_ids";
const QUESTIONS_PER_SESSION = 8;

function getSeenIds(): Set<string> {
  try {
    const raw = localStorage.getItem(SEEN_KEY);
    if (!raw) return new Set();
    const arr = JSON.parse(raw) as string[];
    return new Set(arr);
  } catch {
    return new Set();
  }
}

function saveSeenIds(ids: Set<string>): void {
  try {
    localStorage.setItem(SEEN_KEY, JSON.stringify([...ids]));
  } catch {
    // ignore
  }
}

function shuffleArray<T>(arr: T[]): T[] {
  const a = [...arr];
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}

/**
 * Pick QUESTIONS_PER_SESSION questions that haven't been seen yet.
 * If unseen pool is exhausted for the category/language, reset and start fresh.
 */
export function pickUniqueQuestions(
  pool: Question[],
  count = QUESTIONS_PER_SESSION,
): Question[] {
  if (pool.length === 0) return [];

  const seen = getSeenIds();
  let unseen = pool.filter((q) => !seen.has(String(q.id)));

  // If not enough unseen questions, reset the pool for this set
  if (unseen.length < count) {
    // Remove the IDs of current pool from seen so they become available again
    const poolIds = new Set(pool.map((q) => String(q.id)));
    const newSeen = new Set([...seen].filter((id) => !poolIds.has(id)));
    saveSeenIds(newSeen);
    unseen = [...pool];
  }

  const selected = shuffleArray(unseen).slice(0, count);
  const newSeen = getSeenIds();
  for (const q of selected) newSeen.add(String(q.id));
  saveSeenIds(newSeen);

  return selected;
}

export function getFallbackQuestions(
  category: string,
  language: Language,
): Question[] {
  const pool = SAMPLE_QUESTIONS.filter(
    (q) => q.category === category && q.language === language,
  );
  return pickUniqueQuestions(pool);
}

export function getAllQuestionsForCategory(
  category: string,
  language: Language,
): Question[] {
  return SAMPLE_QUESTIONS.filter(
    (q) => q.category === category && q.language === language,
  );
}
