import { Difficulty, Language, type Question } from "../backend";

const bq = (
  id: number,
  cat: string,
  text: string,
  opts: string[],
  ci: number,
  diff = Difficulty.medium,
): Question => ({
  id: BigInt(id),
  category: cat,
  language: Language.bengali,
  questionText: text,
  options: opts,
  correctIndex: BigInt(ci),
  difficulty: diff,
});

const eq = (
  id: number,
  cat: string,
  text: string,
  opts: string[],
  ci: number,
  diff = Difficulty.medium,
): Question => ({
  id: BigInt(id),
  category: cat,
  language: Language.english,
  questionText: text,
  options: opts,
  correctIndex: BigInt(ci),
  difficulty: diff,
});

export const SAMPLE_QUESTIONS: Question[] = [
  // ===== General Knowledge - Bengali =====
  bq(
    1001,
    "General Knowledge",
    "বাংলাদেশের জাতীয় ফুল কোনটি?",
    ["গোলাপ", "শাপলা", "জবা", "পদ্ম"],
    1,
    Difficulty.easy,
  ),
  bq(
    1002,
    "General Knowledge",
    "বাংলাদেশের রাজধানী কোথায়?",
    ["চট্টগ্রাম", "সিলেট", "ঢাকা", "রাজশাহী"],
    2,
    Difficulty.easy,
  ),
  bq(
    1003,
    "General Knowledge",
    "পৃথিবীর সবচেয়ে বড় মহাসাগর কোনটি?",
    ["আটলান্টিক", "ভারত", "প্রশান্ত", "আর্কটিক"],
    2,
    Difficulty.easy,
  ),
  bq(
    1004,
    "General Knowledge",
    "বাংলাদেশের মুক্তিযুদ্ধ কত সালে হয়েছিল?",
    ["১৯৬৯", "১৯৭০", "১৯৭১", "১৯৭২"],
    2,
    Difficulty.easy,
  ),
  bq(
    1005,
    "General Knowledge",
    "বাংলাদেশের জাতীয় পাখি কোনটি?",
    ["ময়ূর", "দোয়েল", "কোকিল", "শালিক"],
    1,
    Difficulty.easy,
  ),
  bq(
    1006,
    "General Knowledge",
    "সূর্য থেকে পৃথিবীর দূরত্ব প্রায় কত?",
    [
      "১৪ কোটি কিলোমিটার",
      "১৫ কোটি কিলোমিটার",
      "১৬ কোটি কিলোমিটার",
      "১৭ কোটি কিলোমিটার",
    ],
    1,
  ),
  bq(
    1007,
    "General Knowledge",
    "বাংলাদেশের জাতীয় খেলা কী?",
    ["ক্রিকেট", "ফুটবল", "হা-ডু-ডু (কাবাডি)", "হকি"],
    2,
  ),
  bq(
    1008,
    "General Knowledge",
    "UNESCO কোন বছর বাংলাকে আন্তর্জাতিক মাতৃভাষা দিবস হিসেবে স্বীকৃতি দেয়?",
    ["১৯৯৮", "১৯৯৯", "২০০০", "২০০১"],
    1,
  ),

  // ===== Science - Bengali =====
  bq(
    2001,
    "Science",
    "পানির রাসায়নিক সংকেত কী?",
    ["CO₂", "H₂O", "NaCl", "O₂"],
    1,
    Difficulty.easy,
  ),
  bq(
    2002,
    "Science",
    "আলোর গতিবেগ প্রতি সেকেন্ডে কত?",
    ["২ লক্ষ কিমি", "৩ লক্ষ কিমি", "৪ লক্ষ কিমি", "১ লক্ষ কিমি"],
    1,
    Difficulty.easy,
  ),
  bq(
    2003,
    "Science",
    "মানব দেহে হাড়ের সংখ্যা কত?",
    ["২০৬", "২০৮", "২১০", "২০৪"],
    0,
  ),
  bq(
    2004,
    "Science",
    "কোন গ্যাস বায়ুমণ্ডলে সবচেয়ে বেশি আছে?",
    ["অক্সিজেন", "কার্বন ডাইঅক্সাইড", "নাইট্রোজেন", "হিলিয়াম"],
    2,
    Difficulty.easy,
  ),
  bq(
    2005,
    "Science",
    "পৃথিবীর নিজ অক্ষের চারপাশে একবার ঘুরতে কত সময় লাগে?",
    ["১২ ঘণ্টা", "২৪ ঘণ্টা", "৪৮ ঘণ্টা", "৩৬ ঘণ্টা"],
    1,
    Difficulty.easy,
  ),
  bq(
    2006,
    "Science",
    "সূর্যের আলো পৃথিবীতে পৌঁছাতে কত মিনিট লাগে?",
    ["৫ মিনিট", "৮ মিনিট", "১২ মিনিট", "১৫ মিনিট"],
    1,
  ),
  bq(
    2007,
    "Science",
    "DNA-এর পূর্ণরূপ কী?",
    [
      "Deoxyribonucleic Acid",
      "Diribonuclear Acid",
      "Deoxyribose Acid",
      "Dynamic Nucleic Acid",
    ],
    0,
    Difficulty.hard,
  ),
  bq(
    2008,
    "Science",
    "মানবদেহের সবচেয়ে বড় অঙ্গ কোনটি?",
    ["হৃদপিণ্ড", "মস্তিষ্ক", "ত্বক", "যকৃৎ"],
    2,
  ),

  // ===== History - Bengali =====
  bq(
    3001,
    "History",
    "বাংলাদেশের স্বাধীনতা দিবস কত তারিখে?",
    ["১৬ ডিসেম্বর", "২৬ মার্চ", "১৫ আগস্ট", "২১ ফেব্রুয়ারি"],
    1,
    Difficulty.easy,
  ),
  bq(
    3002,
    "History",
    "বঙ্গবন্ধু শেখ মুজিবুর রহমানের জন্ম কত সালে?",
    ["১৯১৮", "১৯২০", "১৯২২", "১৯২৪"],
    1,
    Difficulty.easy,
  ),
  bq(
    3003,
    "History",
    "ভাষা আন্দোলন কত সালে হয়েছিল?",
    ["১৯৫০", "১৯৫২", "১৯৫৪", "১৯৫৬"],
    1,
    Difficulty.easy,
  ),
  bq(
    3004,
    "History",
    "মোগল সাম্রাজ্যের প্রতিষ্ঠাতা কে?",
    ["আকবর", "বাবর", "হুমায়ুন", "জাহাঙ্গীর"],
    1,
  ),
  bq(
    3005,
    "History",
    "প্রথম বিশ্বযুদ্ধ কত সালে শুরু হয়েছিল?",
    ["১৯১২", "১৯১৪", "১৯১৬", "১৯১৮"],
    1,
    Difficulty.easy,
  ),
  bq(
    3006,
    "History",
    "ব্রিটিশরা ভারত ছেড়ে যায় কত সালে?",
    ["১৯৪৫", "১৯৪৬", "১৯৪৭", "১৯৪৮"],
    2,
  ),
  bq(
    3007,
    "History",
    "বাংলাদেশের প্রথম রাষ্ট্রপতি কে ছিলেন?",
    ["শেখ মুজিবুর রহমান", "তাজউদ্দীন আহমদ", "সৈয়দ নজরুল ইসলাম", "জিয়াউর রহমান"],
    0,
  ),
  bq(
    3008,
    "History",
    "বিজয় দিবস কত তারিখে?",
    ["১৬ ডিসেম্বর", "২৬ মার্চ", "১৫ আগস্ট", "৭ মার্চ"],
    0,
    Difficulty.easy,
  ),

  // ===== Sports - Bengali =====
  bq(
    4001,
    "Sports",
    "ক্রিকেটে একটি ওভারে কতটি বল থাকে?",
    ["৪টি", "৫টি", "৬টি", "৮টি"],
    2,
    Difficulty.easy,
  ),
  bq(
    4002,
    "Sports",
    "ফুটবল বিশ্বকাপ কত বছর পরপর অনুষ্ঠিত হয়?",
    ["২ বছর", "৩ বছর", "৪ বছর", "৫ বছর"],
    2,
    Difficulty.easy,
  ),
  bq(
    4003,
    "Sports",
    "অলিম্পিক গেমস কত বছর পরপর হয়?",
    ["২ বছর", "৪ বছর", "৬ বছর", "৮ বছর"],
    1,
    Difficulty.easy,
  ),
  bq(
    4004,
    "Sports",
    "বাংলাদেশ ক্রিকেট দলের অধিনায়ক (২০২৪) কে?",
    ["সাকিব আল হাসান", "তামিম ইকবাল", "মাশরাফি বিন মুর্তজা", "নাজমুল হোসেন শান্ত"],
    3,
  ),
  bq(
    4005,
    "Sports",
    "টেনিসে সবচেয়ে বেশি গ্র্যান্ড স্ল্যাম জিতেছেন কে?",
    ["রজার ফেদেরার", "নোভাক জোকোভিচ", "রাফায়েল নাদাল", "পিট সাম্প্রাস"],
    1,
    Difficulty.hard,
  ),
  bq(
    4006,
    "Sports",
    "ফিফা বিশ্বকাপ ২০২২ কোন দেশ জিতেছে?",
    ["ফ্রান্স", "ব্রাজিল", "আর্জেন্টিনা", "জার্মানি"],
    2,
  ),
  bq(
    4007,
    "Sports",
    "ক্রিকেটে 'হ্যাটট্রিক' মানে কী?",
    ["তিনটি সিক্স", "তিনটি চার", "পরপর তিন বলে তিন উইকেট", "পরপর তিন বলে তিন রান"],
    2,
  ),
  bq(
    4008,
    "Sports",
    "বাংলাদেশের জাতীয় খেলার মাঠ কোথায়?",
    ["মিরপুর স্টেডিয়াম", "বঙ্গবন্ধু জাতীয় স্টেডিয়াম", "চট্টগ্রাম স্টেডিয়াম", "সিলেট স্টেডিয়াম"],
    1,
  ),

  // ===== General Knowledge - English =====
  eq(
    5001,
    "General Knowledge",
    "What is the capital of Bangladesh?",
    ["Chittagong", "Sylhet", "Dhaka", "Rajshahi"],
    2,
    Difficulty.easy,
  ),
  eq(
    5002,
    "General Knowledge",
    "What is the largest ocean on Earth?",
    ["Atlantic", "Indian", "Pacific", "Arctic"],
    2,
    Difficulty.easy,
  ),
  eq(
    5003,
    "General Knowledge",
    "How many continents are there on Earth?",
    ["5", "6", "7", "8"],
    2,
    Difficulty.easy,
  ),
  eq(
    5004,
    "General Knowledge",
    "Which planet is known as the Red Planet?",
    ["Venus", "Jupiter", "Saturn", "Mars"],
    3,
    Difficulty.easy,
  ),
  eq(
    5005,
    "General Knowledge",
    "What is the national flower of Bangladesh?",
    ["Rose", "Shapla (Water Lily)", "Jasmine", "Lotus"],
    1,
    Difficulty.easy,
  ),
  eq(
    5006,
    "General Knowledge",
    "How many days are in a leap year?",
    ["364", "365", "366", "367"],
    2,
    Difficulty.easy,
  ),
  eq(
    5007,
    "General Knowledge",
    "What is the smallest country in the world?",
    ["Monaco", "San Marino", "Liechtenstein", "Vatican City"],
    3,
  ),
  eq(
    5008,
    "General Knowledge",
    "How many bones are in the adult human body?",
    ["204", "206", "208", "210"],
    1,
  ),

  // ===== Science - English =====
  eq(
    6001,
    "Science",
    "What is the chemical formula for water?",
    ["CO₂", "H₂O", "NaCl", "O₂"],
    1,
    Difficulty.easy,
  ),
  eq(
    6002,
    "Science",
    "What is the speed of light?",
    ["200,000 km/s", "300,000 km/s", "400,000 km/s", "150,000 km/s"],
    1,
    Difficulty.easy,
  ),
  eq(
    6003,
    "Science",
    "Which gas makes up most of Earth's atmosphere?",
    ["Oxygen", "Carbon Dioxide", "Nitrogen", "Helium"],
    2,
    Difficulty.easy,
  ),
  eq(
    6004,
    "Science",
    "How many chambers does the human heart have?",
    ["2", "3", "4", "5"],
    2,
    Difficulty.easy,
  ),
  eq(
    6005,
    "Science",
    "What is the powerhouse of the cell?",
    ["Nucleus", "Ribosome", "Mitochondria", "Golgi apparatus"],
    2,
  ),
  eq(
    6006,
    "Science",
    "How long does it take sunlight to reach Earth?",
    ["5 minutes", "8 minutes", "12 minutes", "15 minutes"],
    1,
  ),
  eq(
    6007,
    "Science",
    "What is the atomic number of carbon?",
    ["4", "6", "8", "12"],
    1,
  ),
  eq(
    6008,
    "Science",
    "What is DNA?",
    ["A protein", "A lipid", "A nucleic acid", "A carbohydrate"],
    2,
    Difficulty.hard,
  ),

  // ===== History - English =====
  eq(
    7001,
    "History",
    "When did Bangladesh gain independence?",
    ["1969", "1970", "1971", "1972"],
    2,
    Difficulty.easy,
  ),
  eq(
    7002,
    "History",
    "Who was the first President of the United States?",
    [
      "Thomas Jefferson",
      "John Adams",
      "George Washington",
      "Benjamin Franklin",
    ],
    2,
    Difficulty.easy,
  ),
  eq(
    7003,
    "History",
    "In which year did World War II end?",
    ["1943", "1944", "1945", "1946"],
    2,
    Difficulty.easy,
  ),
  eq(
    7004,
    "History",
    "Who was the founder of the Mughal Empire?",
    ["Akbar", "Babur", "Humayun", "Jahangir"],
    1,
  ),
  eq(
    7005,
    "History",
    "The Language Movement in Bangladesh occurred in which year?",
    ["1950", "1952", "1954", "1956"],
    1,
    Difficulty.easy,
  ),
  eq(
    7006,
    "History",
    "Which country was the first to give women the right to vote?",
    ["USA", "UK", "New Zealand", "France"],
    2,
  ),
  eq(
    7007,
    "History",
    "Who built the Taj Mahal?",
    ["Akbar", "Shah Jahan", "Aurangzeb", "Jahangir"],
    1,
  ),
  eq(
    7008,
    "History",
    "When did the Berlin Wall fall?",
    ["1987", "1988", "1989", "1990"],
    2,
  ),

  // ===== Sports - English =====
  eq(
    8001,
    "Sports",
    "How many balls are in an over in cricket?",
    ["4", "5", "6", "8"],
    2,
    Difficulty.easy,
  ),
  eq(
    8002,
    "Sports",
    "How often is the FIFA World Cup held?",
    ["Every 2 years", "Every 3 years", "Every 4 years", "Every 5 years"],
    2,
    Difficulty.easy,
  ),
  eq(
    8003,
    "Sports",
    "How many players are in a football (soccer) team?",
    ["9", "10", "11", "12"],
    2,
    Difficulty.easy,
  ),
  eq(
    8004,
    "Sports",
    "Who won the FIFA World Cup 2022?",
    ["France", "Brazil", "Argentina", "Germany"],
    2,
  ),
  eq(
    8005,
    "Sports",
    "How many Olympic rings are there?",
    ["4", "5", "6", "7"],
    1,
    Difficulty.easy,
  ),
  eq(
    8006,
    "Sports",
    "Which sport uses a shuttlecock?",
    ["Tennis", "Squash", "Badminton", "Table Tennis"],
    2,
    Difficulty.easy,
  ),
  eq(
    8007,
    "Sports",
    "Who holds the most Grand Slam titles in tennis?",
    ["Roger Federer", "Novak Djokovic", "Rafael Nadal", "Pete Sampras"],
    1,
    Difficulty.hard,
  ),
  eq(
    8008,
    "Sports",
    "How long is a standard marathon race?",
    ["40 km", "42.195 km", "45 km", "38 km"],
    1,
  ),
];

export function getFallbackQuestions(
  category: string,
  language: Language,
): Question[] {
  return SAMPLE_QUESTIONS.filter(
    (q) => q.category === category && q.language === language,
  );
}
