/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Difficulty = IDL.Variant({
  'easy' : IDL.Null,
  'hard' : IDL.Null,
  'medium' : IDL.Null,
});
export const Language = IDL.Variant({
  'bengali' : IDL.Null,
  'english' : IDL.Null,
});
export const Question = IDL.Record({
  'id' : IDL.Nat,
  'correctIndex' : IDL.Nat,
  'difficulty' : Difficulty,
  'questionText' : IDL.Text,
  'language' : Language,
  'category' : IDL.Text,
  'options' : IDL.Vec(IDL.Text),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const ScoreEntry = IDL.Record({
  'id' : IDL.Nat,
  'score' : IDL.Nat,
  'language' : Language,
  'totalQuestions' : IDL.Nat,
  'timestamp' : IDL.Int,
  'playerName' : IDL.Text,
  'category' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addQuestion' : IDL.Func([Question], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteQuestion' : IDL.Func([IDL.Nat], [], []),
  'getAllQuestions' : IDL.Func([], [IDL.Vec(Question)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getLeaderboard' : IDL.Func([], [IDL.Vec(ScoreEntry)], ['query']),
  'getLeaderboardByCategory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ScoreEntry)],
      ['query'],
    ),
  'getQuestionsByCategory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Question)],
      ['query'],
    ),
  'getQuestionsByCategoryAndLanguage' : IDL.Func(
      [IDL.Text, Language],
      [IDL.Vec(Question)],
      ['query'],
    ),
  'getQuestionsByLanguage' : IDL.Func(
      [Language],
      [IDL.Vec(Question)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initializeData' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitScore' : IDL.Func([ScoreEntry], [ScoreEntry], []),
  'updateQuestion' : IDL.Func([IDL.Nat, Question], [], []),
  'verifyAdminPassword' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Difficulty = IDL.Variant({
    'easy' : IDL.Null,
    'hard' : IDL.Null,
    'medium' : IDL.Null,
  });
  const Language = IDL.Variant({ 'bengali' : IDL.Null, 'english' : IDL.Null });
  const Question = IDL.Record({
    'id' : IDL.Nat,
    'correctIndex' : IDL.Nat,
    'difficulty' : Difficulty,
    'questionText' : IDL.Text,
    'language' : Language,
    'category' : IDL.Text,
    'options' : IDL.Vec(IDL.Text),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const ScoreEntry = IDL.Record({
    'id' : IDL.Nat,
    'score' : IDL.Nat,
    'language' : Language,
    'totalQuestions' : IDL.Nat,
    'timestamp' : IDL.Int,
    'playerName' : IDL.Text,
    'category' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addQuestion' : IDL.Func([Question], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteQuestion' : IDL.Func([IDL.Nat], [], []),
    'getAllQuestions' : IDL.Func([], [IDL.Vec(Question)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getLeaderboard' : IDL.Func([], [IDL.Vec(ScoreEntry)], ['query']),
    'getLeaderboardByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ScoreEntry)],
        ['query'],
      ),
    'getQuestionsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Question)],
        ['query'],
      ),
    'getQuestionsByCategoryAndLanguage' : IDL.Func(
        [IDL.Text, Language],
        [IDL.Vec(Question)],
        ['query'],
      ),
    'getQuestionsByLanguage' : IDL.Func(
        [Language],
        [IDL.Vec(Question)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initializeData' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitScore' : IDL.Func([ScoreEntry], [ScoreEntry], []),
    'updateQuestion' : IDL.Func([IDL.Nat, Question], [], []),
    'verifyAdminPassword' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };