/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Difficulty = { 'easy' : null } |
  { 'hard' : null } |
  { 'medium' : null };
export type Language = { 'bengali' : null } |
  { 'english' : null };
export interface Question {
  'id' : bigint,
  'correctIndex' : bigint,
  'difficulty' : Difficulty,
  'questionText' : string,
  'language' : Language,
  'category' : string,
  'options' : Array<string>,
}
export interface ScoreEntry {
  'id' : bigint,
  'score' : bigint,
  'language' : Language,
  'totalQuestions' : bigint,
  'timestamp' : bigint,
  'playerName' : string,
  'category' : string,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addQuestion' : ActorMethod<[Question], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteQuestion' : ActorMethod<[bigint], undefined>,
  'getAllQuestions' : ActorMethod<[], Array<Question>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getLeaderboard' : ActorMethod<[], Array<ScoreEntry>>,
  'getLeaderboardByCategory' : ActorMethod<[string], Array<ScoreEntry>>,
  'getQuestionsByCategory' : ActorMethod<[string], Array<Question>>,
  'getQuestionsByCategoryAndLanguage' : ActorMethod<
    [string, Language],
    Array<Question>
  >,
  'getQuestionsByLanguage' : ActorMethod<[Language], Array<Question>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initializeData' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitScore' : ActorMethod<[ScoreEntry], ScoreEntry>,
  'updateQuestion' : ActorMethod<[bigint, Question], undefined>,
  'verifyAdminPassword' : ActorMethod<[string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];